default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: code_mapping_development

test:
  <<: *default
  database: code_mapping_test

production:
  <<: *default
  database: code_mapping_production
  url:  <%= ENV["DATABASE_URL"] %>
  pool: <%= ENV["DB_POOL"] || ENV['RAILS_MAX_THREADS'] || 5 %>
